### ISSUE TITLE
use[eventName]Listener doesn't work as dependency in another hooks

### ISSUE THREAD

**Issue by kwiat1990** [etienne-martin/react-event-hook#21]
Hey, I have a bunch of listeners functions, which make some API calls. After each such call, I want to re-fetch some data, so in order to do that I use `useEffect` hook and set all those listener functions as dependencies but despite they all get called, they don't have any impact on `useEffect` and I'm not sure why.

The simplified code looks like this:
```js
const fetchData = useCallback(async () => {
    await getData(id);
  }, [id]);

  useEffect(() => {
    if (!data.length) {
      fetchData();
    }
  }, [
    data.length,
    useUpdateCommentListener,
  ]);

  useUpdateCommentListener(async (id) => {
    await putComment(id);
  });
```

**Comment by etienne-martin** [comment]
This is expected, that's because the listener function's reference stays the same. 

There are multiple ways to do what you're trying to do. One of them is to trigger the re-fetch directly from the handler:

```javascript
useUpdateCommentListener(async (id) => {
  await putComment(id);
  await fetchData();
});
```

Another approach is to update a local state from the listener whenever it gets called, and then add that piece of state to the useEffect dependencies:

```javascript
const [updatedCommentId, setUpdatedCommentId] = useState(null);

useEffect(() => {
  // Will be called whenever `updatedCommentId` changes
}, [updatedCommentId]);

useUpdateCommentListener(async (id) => {
  await putComment(id);
  setUpdatedCommentId(id);
});
```

**Comment by etienne-martin** [comment]
I can put together a demo if you can provide a minimal reproduction of the issue on codesandbox.

**Comment by kwiat1990** [comment]
I came up with the same two ideas how to solve this. I ended up with something in the middle using SWR for fetching data and calling mutate function directly in other comment services.

**Comment by etienne-martin** [comment]
Glad you figured it out

**Comment by kwiat1990** [comment]
@etienne-martin I encountered another interesting problem: I use Next.js along with Next Auth and on errors I set a global snackbar using your plugin. It does work from within axios response interceptor and from other components. But somehow it doesn't work if I get an error from login providers such as Google. In such case after there's a redirect from provider's site back to the login page (with a normal page reload). On the login page I read error from query parameters and I emit an event. I can see that the event gets emitted but the listener placed in the `_app.ts` doesn't get called. What's more interesting, if I place this listener in a component nested in the ´_app.ts´, it gets called.

If I use instead of events a custom react context, it also does work. 

I'm not sure how I could create a sandbox to illustrate the problem.

**Comment by etienne-martin** [comment]
Sounds like you are emitting the event from the server, but listeners live on the client.

I would read the error from the query params, pass that to your login page component, and then emit the event from inside a `useEffect` so that it gets emitted from the client.

**Comment by etienne-martin** [comment]
To clarify, are you emitting the event from inside a `getInitialProps` or `getServerSideProps`?

**Comment by kwiat1990** [comment]
Nope, it’s all in the client and I indeed emit that event from inside `useEffect`. It seems to be really odd behavior I would say as the overall flow is pretty the same as for other events I use. The only difference is that it happens more or less on mount.

**Comment by etienne-martin** [comment]
Ok so you used something like `useRouter` to retrieve the error query param?

**Comment by kwiat1990** [comment]
Yeah, and it does work correctly. I’m able to emit that event and listen to it in a navbar component (it’s the nested component in which the whole flow works). Why it doesn’t in the `_app.ts` I really don’t know.

**Comment by etienne-martin** [comment]
Pretty sure this is not the issue but I added a warning when emitting events from the server in case someone tries to do that.

- https://github.com/etienne-martin/react-event-hook/pull/22

**Comment by etienne-martin** [comment]
> Yeah, and it does work correctly. I’m able to emit that event and listen to it in a navbar component (it’s the nested component in which the whole flow works). Why it doesn’t in the `_app.ts` I really don’t know.

This is weird though, I know that next.js does some sort of black magic with `_app.ts`. I can take a look at the issue if you can provide a minimal reproduction. This can either be a public repo that I can pull or a codesandbox:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/9700213/168678749-f3460cfc-c0a5-4656-9203-e0502fcae270.png">

**Comment by kwiat1990** [comment]
@etienne-martin it seems like events won't get intercepted on route params change. Here a sandbox: https://codesandbox.io/s/priceless-mountain-7otxq3?file=/pages/index.js, in which you can see that an event gets emitted after params got changed. This is the same behaviour I saw in my app: the emit function is called but not the listener.

**Comment by etienne-martin** [comment]
Thanks for the link. I played around with the sandbox and realized this has nothing to do with next.js.

I've been able to reproduce the issue in a barebone react project. The problem occurs when a listener is registered on a component that renders a children which emits.

Sort of like this:
- `<ParentComponent />`
  - calls usePingListener
  - `<ChildComponent />`
    - calls emitPing

What happens is that the `useEffect` in the child component get executed before the `useEffect` of the parent. This library uses `useEffect` to bind its listeners so by the time the listener is registered, the event has already been emitted by the children.

Thanks again, I'll try to roll out a fix for that pretty soon.

**Comment by kwiat1990** [comment]
Cool! I had no idea how the execution stack looks like. I was expecting something quite opposite - a top-down order.

I’m looking forward to the fix as I find your plugin excellent. It’s tiny and tailored to my project’s needs.

Btw. should we split this issue as the initial question was answered at the beginning? Or perhaps you manage to enable this feature, so one could set listener as dependency?

**Comment by etienne-martin** [comment]
I created a separate issue ☝️
