### ISSUE TITLE
Listeners should be registered before child components have a chance to emit

### ISSUE THREAD

**Issue by etienne-martin** [etienne-martin/react-event-hook#23]
I've been able to reproduce the issue in a barebone react project. The problem occurs when a listener is registered on a component that renders a children which emits.

Sort of like this:
- `<ParentComponent />`
  - calls usePingListener
  - `<ChildComponent />`
    - calls emitPing

What happens is that the `useEffect` in the child component get executed before the `useEffect` of the parent. This library uses `useEffect` to bind its listeners so by the time the listener is registered, the event has already been emitted by the children.

Thanks again, I'll try to roll out a fix for that pretty soon.

_Originally posted by @etienne-martin in https://github.com/etienne-martin/react-event-hook/issues/21#issuecomment-1129127358_

**Comment by etienne-martin** [comment]
Fixed in [version 3.0.4](https://www.npmjs.com/package/react-event-hook/v/3.0.4)

**Comment by etienne-martin** [comment]
CC: @kwiat1990

**Comment by kwiat1990** [comment]
Thanks for the quick fix! I have tried it out and it does work now as expected.

**Comment by etienne-martin** [comment]
Great, glad it fixed your issue, thanks again
